### ISSUE TITLE
Process is being used in the browser (it should only be used in Node.js)

### ISSUE THREAD

**Issue by PaulFidika** [lisajamhoury/simple-peer-wrapper#5]
![Screenshot 2022-03-29 003910](https://user-images.githubusercontent.com/33161696/160549258-4028020c-ece5-4d83-9b25-b1ac1b13e583.png)

As far as I can tell, this library is unusable. The problem is that it's maybe references to a readable_stream, and the library implementing this is making a call to process.nextTick(), however this function only exists within Node.js environment, not within a browser environment. I've attempted to fix this by adding process plugins to my webpack configuration (I'm using react for the client), but thus far I've been unsuccessful.

**Comment by lisajamhoury** [comment]
Can you provide some context / code?

**Comment by krazyjakee** [comment]
To recreate:
- Use `create-react-app` to create a blank project.
- Implement the basic example listed in readmes.

The issue is with the `readable-stream` dependency that is being compiled into `dist` here: https://github.com/lisajamhoury/simple-peer-wrapper/blob/9b7fde3774eaaf6f1cd24e85bdf441b44abd80c6/dist/simple-peer-wrapper.js#L5292
